function extractVideoId(sourceUrl = '') {
  const text = String(sourceUrl || '');
  const modalMatch = text.match(/[?&]modal_id=(\d{12,})/i);
  if (modalMatch) return modalMatch[1];
  const pathMatch = text.match(/\/video\/(\d{12,})/i);
  if (pathMatch) return pathMatch[1];
  const numericMatch = text.match(/(\d{12,})/);
  return numericMatch ? numericMatch[1] : 'demo';
}

function buildDemoAnalysis(sourceUrl) {
  const videoId = extractVideoId(sourceUrl);
  const products = [
    {
      name: '温和洁面乳',
      brand: 'DemoLab',
      category: '洁面',
      appearance_times: [8],
      evidence_refs: ['e1'],
      confidence: 0.96,
    },
    {
      name: '舒缓补水喷雾',
      brand: 'DemoLab',
      category: '补水',
      appearance_times: [22],
      evidence_refs: ['e2'],
      confidence: 0.93,
    },
    {
      name: '维稳精华',
      brand: 'DemoLab',
      category: '精华',
      appearance_times: [37],
      evidence_refs: ['e3'],
      confidence: 0.91,
    },
    {
      name: '轻薄修护面霜',
      brand: 'DemoLab',
      category: '保湿',
      appearance_times: [51],
      evidence_refs: ['e4'],
      confidence: 0.95,
    },
  ];

  return {
    video_id: videoId,
    source_url: sourceUrl,
    content_type: 'skincare_recommendation',
    products,
    recommend_reasons: [
      { product_refs: ['温和洁面乳'], reason: '演示回退：先清洁再护肤，流程更完整。' },
      { product_refs: ['舒缓补水喷雾'], reason: '演示回退：补水步骤可以缓解紧绷。' },
      { product_refs: ['维稳精华'], reason: '演示回退：轻量精华用于日常维稳。' },
      { product_refs: ['轻薄修护面霜'], reason: '演示回退：最后一步锁水修护。' },
    ],
    claimed_effects: [
      { product_refs: ['温和洁面乳'], effect: '帮助清洁多余油脂和残留。' },
      { product_refs: ['舒缓补水喷雾'], effect: '帮助补水并缓解干燥感。' },
      { product_refs: ['维稳精华'], effect: '帮助维持皮肤稳定状态。' },
      { product_refs: ['轻薄修护面霜'], effect: '帮助锁住水分并修护屏障。' },
    ],
    skin_types: [
      { product_refs: ['温和洁面乳'], text: '适合日常通勤护肤。' },
      { product_refs: ['轻薄修护面霜'], text: '适合偏干或混合肤质。' },
    ],
    usage_context: [
      { product_refs: ['温和洁面乳'], context: '早晚作为第一步使用。' },
      { product_refs: ['舒缓补水喷雾'], context: '洁面后补水使用。' },
      { product_refs: ['维稳精华'], context: '补水后薄涂。' },
      { product_refs: ['轻薄修护面霜'], context: '最后一步薄涂锁水。' },
    ],
    evidence: [
      {
        id: 'e1',
        source_type: 'demo',
        source_ref: 'fallback',
        observed_text: '演示数据：洁面产品出现于护肤流程开头。',
        visual_description: 'Demo fallback analysis item 1',
        confidence: 0.9,
      },
      {
        id: 'e2',
        source_type: 'demo',
        source_ref: 'fallback',
        observed_text: '演示数据：补水步骤紧随洁面之后。',
        visual_description: 'Demo fallback analysis item 2',
        confidence: 0.9,
      },
      {
        id: 'e3',
        source_type: 'demo',
        source_ref: 'fallback',
        observed_text: '演示数据：精华用于中段维稳。',
        visual_description: 'Demo fallback analysis item 3',
        confidence: 0.9,
      },
      {
        id: 'e4',
        source_type: 'demo',
        source_ref: 'fallback',
        observed_text: '演示数据：面霜用于最后锁水。',
        visual_description: 'Demo fallback analysis item 4',
        confidence: 0.9,
      },
    ],
    uncertain_items: ['后端不可用，已切换为演示数据'],
    missing_evidence: [],
    quality_notes: [
      'Demo fallback generated by Netlify function when backend is unavailable.',
    ],
    is_demo_fallback: true,
  };
}

function buildDemoResponse(sourceUrl, detail) {
  const analysis = buildDemoAnalysis(sourceUrl);
  return {
    success: true,
    video_id: analysis.video_id,
    markdown: [
      '# Demo Analysis',
      '',
      `- Source URL: ${sourceUrl}`,
      `- Fallback: ${detail}`,
    ].join('\n'),
    analysis,
  };
}

async function proxyToBackend(backend, body) {
  const response = await fetch(`${backend}/analyze-video`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body,
  });
  const raw = await response.text();
  if (!response.ok) {
    throw new Error(raw || `Backend responded with HTTP ${response.status}`);
  }

  try {
    const parsed = JSON.parse(raw);
    if (parsed && parsed.analysis) {
      return {
        statusCode: 200,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(parsed),
      };
    }
  } catch {
    // Fall through to demo fallback.
  }

  throw new Error('Backend response did not contain a valid analysis payload');
}

exports.handler = async (event) => {
  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ detail: 'Method not allowed' }),
    };
  }

  let payload = {};
  try {
    payload = JSON.parse(event.body || '{}');
  } catch {
    payload = {};
  }

  const sourceUrl = String(payload.url || '').trim();
  if (!sourceUrl) {
    return {
      statusCode: 400,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ detail: 'url is required' }),
    };
  }

  const backend = (process.env.BACKEND_URL || process.env.VITE_API_BASE || '').replace(/\/$/, '');
  if (!backend) {
    return {
      statusCode: 200,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(buildDemoResponse(sourceUrl, 'BACKEND_URL is not configured')),
    };
  }

  try {
    return await proxyToBackend(backend, event.body);
  } catch (error) {
    return {
      statusCode: 200,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(buildDemoResponse(sourceUrl, `backend unavailable: ${error.message}`)),
    };
  }
};
